TC_00.002.03 |US_02.007 | Pipeline > Rename project
RedRoverSchool/JenkinsQA_07 pull request #1101
Opened 2023-10-27 17:56 UTC by Forostinko

https://trello.com/c/0yRYSrdB/236-tc0000203-us02007-pipeline-rename-project

2023-10-28 18:01 UTC, judmi requested changes
We need to create classes named after an item type that is being tested, i.e. PipelineTest, Pipeline3Test etc. please change the name of your class

2023-10-28 19:43 UTC, Forostinko commented
> We need to create classes named after an item type that is being tested, i.e. PipelineTest, Pipeline3Test etc. Also class names must end with Test. please change the name of your class.

@judmi My class is named like TC

2023-10-29 06:12 UTC, judmi commented
> > We need to create classes named after an item type that is being tested, i.e. PipelineTest, Pipeline3Test etc. Also class names must end with Test. please change the name of your class.
> 
> 
> 
> @judmi My class is named like TC

It's incorrect. We do not create separate classes for each TC. We create one class in which all tests are logically grouped according to the item whose functionality they test. Here you are testing a functionality of the Pipeline -> the class name shall be PipelineTest / Pipeline[num]Test. Also please fill your trello card with the TC steps and expected results. We need to first write the TCs steps and then automate it

2023-10-30 14:15 UTC, judmi approved these changes

2023-10-31 16:56 UTC, closed without merging