TC_00.001.01 |Creating new item > Creating Freestyle project
RedRoverSchool/JenkinsQA_07 pull request #1137
Opened 2023-10-28 17:35 UTC by AlexAQA2023

https://trello.com/c/2wPpwASb/255-tc0000101-creating-new-item-creating-freestyle-project

2023-10-28 18:04 UTC, judmi requested changes
We need to name classes after the items that are tested in it. e.g. FreestyleProjectTest, Pipeline3Test etc. Your class name is incorrect, please change it

2023-10-28 19:20 UTC, AlexAQA2023 commented
> We need to name classes after the items that are tested in it. e.g. FreestyleProjectTest, Pipeline3Test etc. Your class name is incorrect, please change it

but my test item goal is pipeline creation

2023-10-28 20:53 UTC, VictoriaLema reviewed
@AlexAQA2023 , подскажите, вы создавали вашу карточку Trello из template в бэклоге, либо вы присоединились к уже созданной карточке?

2023-10-28 21:25 UTC, AlexAQA2023 commented
> @AlexAQA2023 , подскажите, вы создавали вашу карточку Trello из template в бэклоге, либо вы присоединились к уже созданной карточке?

взял карточку из To Do и присоединился

2023-10-28 21:26 UTC, AlexAQA2023 commented
> > @AlexAQA2023 , подскажите, вы создавали вашу карточку Trello из template в бэклоге, либо вы присоединились к уже созданной карточке?
> 
> взял карточку из To Do и присоединился

Надо было клонировать?

2023-10-28 21:33 UTC, VictoriaLema commented
Правильно ее создать из образца  в backlog.(но наверно клонировать чужую не запрещено , просто не забыть поменять информацию)28.10.2023, 17:26, "AlexAQA2023" ***@***.***>:


@AlexAQA2023 , подскажите, вы создавали вашу карточку Trello из template в бэклоге, либо вы присоединились к уже созданной карточке?

взял карточку из To Do и присоединился

Надо было клонировать?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

2023-10-28 21:38 UTC, judmi commented
> > We need to name classes after the items that are tested in it. e.g. FreestyleProjectTest, Pipeline3Test etc. Your class name is incorrect, please change it
> 
> 
> 
> but my test item goal is pipeline creation

You're testing pipeline creation -> all tests that test anything connected with a pipeline shall be in a PipelineTest class. That is the class structure that is currently used in the project. We do not create separate classes for each functionality. We create big classes where tests are logically grouped by the item whose functionality they test

2023-10-30 13:42 UTC, AlexAQA2023 commented
> We need to name classes after the items that are tested in it. e.g. FreestyleProjectTest, Pipeline3Test etc. Your class name is incorrect, please change it

done

2023-10-30 13:44 UTC, judmi approved these changes

2023-10-30 17:47 UTC, AstakhovaK approved these changes

2023-10-30 17:48 UTC, merged