refactoring test testCreateMyView2
RedRoverSchool/JenkinsQA_07 pull request #1927
Opened 2023-11-24 22:20 UTC by LaysanNova

https://trello.com/c/TCgnLcfb/861-rf1000104-views-create-view-code-changed-using-pom-methods

2023-11-24 22:49 UTC, AliaksandrMakaranka approved these changes

2023-11-25 09:06 UTC, SafronovaOlga approved these changes

2023-11-25 10:23 UTC, tereshenkov29 commented on src/test/java/school/redrover/ViewTest.java
> +                .goHomePage()
.clickNewItem()
                .typeItemName(JOB_NAME)
                .selectFreestyleProject()
                .clickOk(new NewJobPage(getDriver()))
                .clickSaveButton()
                .goHomePage()
                

а зачем вы вот тут вызываете все эти методы? создание FreeStyle проекта не входит в проверку по тесту, это precondition - значит, можно вынести это (создание) в начало теста - тем более, что служебный метод createNewFreestyleProject в классе уже есть

2023-11-25 10:26 UTC, tereshenkov29 commented on src/test/java/school/redrover/ViewTest.java
> +                .clickNewViewPlus()
а зачем тут новы метод clickNewViewPlus, если уже есть clickNewViewButton, который делает тоже самое?

2023-11-25 10:33 UTC, tereshenkov29 commented on src/test/java/school/redrover/model/NewViewPage.java
> +    public NewViewConfigurePage clickMyViewRadioButton() {
выше есть метод **selectListViewType**, который выполняет аналогичное действие, но с другим типом View - может быть тогда и ваш новый метод стоило бы назвать как **selectMyViewType**?

2023-11-25 10:45 UTC, tereshenkov29 requested changes

2023-11-25 10:45 UTC, tereshenkov29 commented on src/test/java/school/redrover/ViewTest.java
> +                .clickOKButton(new NewViewConfigurePage(getDriver()))
Может быть я что-то неправильно делаю, но после выбора типа MyView и нажатия на Create открывается не страница конфигурации, а страница уже созданного View (страница конфигурации открывается после выбора ListView, но не MyView)

MyView - https://github.com/RedRoverSchool/JenkinsQA_07/assets/50947571/70344117-f6b4-4bab-ae4a-d6f759f6a331

ListView - https://github.com/RedRoverSchool/JenkinsQA_07/assets/50947571/4bbea9d7-eb30-4a2e-969d-acdc4e951e21

И если всё работает так, как на приложенных видео, то параметр для метода clickOKButton указан неправильно, а дальше метод checkLinkToView создан в классе NewViewConfigurePage ошибочно

2023-11-25 10:50 UTC, tereshenkov29 commented on src/test/java/school/redrover/model/MyViewPage.java
> +        nameField.sendKeys(fieldName);
Разве на MyViewPage есть какие-то поля, которые можно заполнять?
по //@[id = 'name'] ничего не находит

![390](https://github.com/RedRoverSchool/JenkinsQA_07/assets/50947571/2738b5af-bb20-4469-8151-b880370565c5)

2023-11-25 10:55 UTC, tereshenkov29 commented on src/test/java/school/redrover/model/MyViewPage.java
> +    private WebElement okButton;
элементы nameField, folderCategory, okButton отсутствуют на MyViewPage, но они есть на странице New View
т.е. в этом классе такие элементы лишние, их нужно отсюда убрать

2023-11-25 14:29 UTC, closed without merging