RF_01.006.14
RedRoverSchool/JenkinsQA_07 pull request #1931
Opened 2023-11-25 11:53 UTC by jokerSharp

https://trello.com/c/fxXFezX4/1043-rf0100614-freestyleproject-configure-general-settings-select-this-project-is-parameterized-checkbox-add-boolean-parameter

testThisProjectIsParameterizedCheckboxAddBooleanParameter was refactored to POM

respective methods were added in FreestyleProjectConfigurePage

2023-11-25 12:24 UTC, tereshenkov29 commented on src/test/java/school/redrover/FreestyleProjectTest.java
> +                .clickSaveButton()
если у вас по тесту в Precondition сказано, что 
> Freestyle project is created.
то может быть есть смысл вынести вызов вот этих методов
                .clickNewItem()
                .createFreestyleProject(PROJECT_NAME)
                .clickSaveButton()
отдельной командой (что-то вида _создатьFreeStyleПроект_) и запустить это до выполнения основной цепочки методов?

2023-11-25 12:25 UTC, tereshenkov29 commented on src/test/java/school/redrover/FreestyleProjectTest.java
> +                .clickConfigure().getParameterNameAndDescription();
если в цепочке методов каждый метод записан на отдельной строке, то надо бы 
getParameterNameAndDescription сдвинуть на строку ниже

2023-11-25 12:29 UTC, tereshenkov29 commented on src/test/java/school/redrover/FreestyleProjectTest.java
> +            Assert.assertEquals(savedParametersList.get(i), parameters.get(i));
а зачем вы используете цикл? если он на самом деле нужен, то может быть стоит спрятать его внутрь вызываемого метода?

насколько я понял по лекциям Сергея, код теста в стиле POM должен выглядеть и читаться так же, как выполнение действий на страницах сайта (т.е. что-то нажать, что-то ввести и т.п.), т.е. имитировать действия как при ручном тесте - а вы вряд ли при ручном тесте как-то выполняете цикл на странице

2023-11-25 12:35 UTC, tereshenkov29 commented on src/test/java/school/redrover/FreestyleProjectTest.java
> +        List<String> parameters = List.of("Ņame", "Description");
читая ваш код, не сразу понял, что это за parameters, у которых что-то get
                .inputParameterName(parameters.get(0))
                .inputParameterDescription(parameters.get(1))
а чем вам не нравился вариант с переменными, который был до этого? субъективно, но отдельные переменные с понятными названиями (name и description) воспринимаются лучше, чем обращение к какому-то элементу в листе

тем более, что эти переменные можно было бы вынести как константы в начало класса

2023-11-25 13:24 UTC, ppashchenkov approved these changes

2023-11-25 13:32 UTC, AliaksandrMakaranka approved these changes

2023-11-25 14:52 UTC, tereshenkov29 requested changes
вам поставили 2 аппрува, но я хотел бы увидеть ваши ответы на мои комменты выше
поэтому пока поставлю Request changes

2023-11-26 11:40 UTC, jokerSharp commented on src/test/java/school/redrover/FreestyleProjectTest.java
> +        List<String> parameters = List.of("Ņame", "Description");
*done

2023-11-26 11:40 UTC, jokerSharp commented on src/test/java/school/redrover/FreestyleProjectTest.java
> +            Assert.assertEquals(savedParametersList.get(i), parameters.get(i));
*done

2023-11-26 11:40 UTC, jokerSharp commented on src/test/java/school/redrover/FreestyleProjectTest.java
> +                .clickConfigure().getParameterNameAndDescription();
*done

2023-11-26 11:40 UTC, jokerSharp commented on src/test/java/school/redrover/FreestyleProjectTest.java
> +                .clickSaveButton()
*done

2023-11-26 12:34 UTC, tereshenkov29 commented on src/test/java/school/redrover/FreestyleProjectTest.java
> +                .clickSaveButton()
сорри, но пока не done

всё еще вижу вызов цепочки методов вместо того, чтобы вызвать один служебный метод для создания проекта перед началом основной части теста

        new HomePage(getDriver())
                .clickNewItem()
                .createFreestyleProject(PROJECT_NAME)
                .goHomePage();

2023-11-26 13:39 UTC, judmi commented on src/test/java/school/redrover/FreestyleProjectTest.java
> +                .clickSaveButton()
Я тут мимокрокодил - можно использовать методы для создания нужной сущности из TestUtils или просто прописать зависимость от теста, который проверяет создание проекта. И тогда не надо будет создавать дополнительные методы

2023-11-26 14:59 UTC, jokerSharp commented on src/test/java/school/redrover/FreestyleProjectTest.java
> +                .clickSaveButton()
*done(2)

2023-11-26 15:00 UTC, tereshenkov29 approved these changes

2023-11-26 15:20 UTC, merged