RF_04.000.11 refactoring method and tests, add method createJob
RedRoverSchool/JenkinsQA_07 pull request #2089
Opened 2023-12-05 17:20 UTC by ekaterinarogozhnikova

https://trello.com/c/5CZq5yOn/1196-rf-0400011-refactoring-tests-and-methods

2023-12-06 00:37 UTC, Olgla approved these changes

2023-12-06 01:28 UTC, Olgla commented on src/test/java/school/redrover/FolderTest.java
>      public void testCreate() {
Наверное, лучше перенести в NewItemPage

2023-12-06 21:36 UTC, VictoriaLema reviewed
Привет. Я описала проблему в классе PipelineTest, но она существует во всех классах.

2023-12-06 21:36 UTC, VictoriaLema commented on src/test/java/school/redrover/PipelineTest.java
> +    private static final String NAME_FOR_SELECT_JOB = "Pipeline";
Привет. Добавление этой переменной "ломает" всю последующую цепочку зависимостей. Во всех тестах используется private static final String JOB_NAME, значение которой = "NewPipeline".

2023-12-06 21:36 UTC, VictoriaLema commented on src/test/java/school/redrover/PipelineTest.java
> -                .createPipeline(JOB_NAME)
здесь создавалась pipeline с именем NewPipeline.

2023-12-06 21:36 UTC, VictoriaLema commented on src/test/java/school/redrover/PipelineTest.java
> +    @Ignore
зависимый тест от testCreatePipeline. Но он ожидает имя NewPipeline (поле JOB_NAME), а оно было исправлено на Pipeline (NAME_FOR_SELECT_JOB)

2023-12-06 21:36 UTC, VictoriaLema commented on src/test/java/school/redrover/PipelineTest.java
> +    @Ignore
зависимый тест от testCreatePipeline. Но он ожидает имя NewPipeline (поле JOB_NAME), а оно было исправлено на Pipeline (NAME_FOR_SELECT_JOB)

2023-12-06 22:41 UTC, VictoriaLema requested changes

2023-12-06 22:41 UTC, VictoriaLema commented on src/test/java/school/redrover/model/NewItemPage.java
> +    public <T> T createJob(String name, String selectedItem, T page) {
Привет. Метод не работает. https://github.com/RedRoverSchool/JenkinsQA_07/actions/runs/7105144854/job/19352403964 в этом коммите видно по скриншотам. Вместо pipeline он создал Multiconfiguration project, в тестах на Folder - FreestyleProject 2 раза и 1 раз Multiconfiguration project

2023-12-06 22:41 UTC, VictoriaLema commented on src/test/java/school/redrover/model/NewItemPage.java
> +    @FindBy(id = "items")
Здесь мы не получаем список элементов items. Мы получаем 1 элемент, - это все, что находится ниже поля для ввода имени

2023-12-07 17:41 UTC, ekaterinarogozhnikova commented on src/test/java/school/redrover/model/NewItemPage.java
> +    @FindBy(id = "items")
@VictoriaLema Добрый день, Виктория, это не тот элемент, который используется в методе. Для метода используется   @FindBy(id = "items")
    private List<WebElement> items;

2023-12-13 17:27 UTC, closed without merging

2023-12-13 17:27 UTC, ekaterinarogozhnikova commented
ветку удаляю