Ainuradj/fist test
RedRoverSchool/JenkinsQA_07 pull request #357
Opened 2023-10-12 05:25 UTC by AinuraDJ

Could you please approve

2023-10-12 11:03 UTC, kbati0104 approved these changes

2023-10-13 09:37 UTC, StoyanaDi requested changes

2023-10-13 09:37 UTC, StoyanaDi commented on src/test/java/school/redrover/GroupQaClimbersTest.java
> +   @Test
regarding changes in this class, instead driver should be used getDriver().

2023-10-14 21:13 UTC, Bezverkhova commented on .github/workflows/ci.yml
> + name: CI
Hi! You've added extra space to row 1 of ci.yml (which we are not allowed to change). You probably should roll back this change.

2023-10-14 21:32 UTC, AinuraDJ commented on .github/workflows/ci.yml
> + name: CI
> Hi! You've added extra space to row 1 of ci.yml (which we are not allowed to change). You probably should roll back this change.

I didn't open  ci.yml file and don't know how to roll it back. Could you please give me some tips?

2023-10-14 22:46 UTC, closed without merging

2023-10-14 22:47 UTC, Bezverkhova commented on .github/workflows/ci.yml
> + name: CI
Now it looks good 👍 Just check next time when you commit and push that there are changes only in your file, because at that moment you can easily roll back accidentally changed files =)
![Снимок экрана 2023-10-14 170953](https://github.com/RedRoverSchool/JenkinsQA_07/assets/60390586/f93d0e24-6c23-4b69-8449-891c29e23b2f)

2023-10-14 22:54 UTC, AinuraDJ commented on .github/workflows/ci.yml
> + name: CI
Thank you very much :))