New test for group Unicorns
RedRoverSchool/JenkinsQA_07 pull request #756
Opened 2023-10-18 23:07 UTC by DmitriNasonov

2023-10-18 23:23 UTC, bzhumanova requested changes

2023-10-18 23:23 UTC, bzhumanova commented on src/test/java/school/redrover/GroupUnicornsTest.java
> +       assertEquals(listOfExpectedItems, extractedTexts);
you need to switch the order: 1 -original result, 2-expected

2023-10-18 23:29 UTC, bzhumanova approved these changes

2023-10-19 00:41 UTC, aizadaM approved these changes

2023-10-19 01:03 UTC, merged