testCreateProject
RedRoverSchool/JenkinsQA_07 pull request #872
Opened 2023-10-21 21:05 UTC by HELZpnz

2023-10-21 22:31 UTC, Michael-Rublev requested changes
Please, correct your test lines:
188 - space skip 
194 - incorrect variable style

2023-10-22 08:39 UTC, EkaterinaSokolova-V approved these changes

2023-10-22 19:58 UTC, EkaterinaSokolova-V commented on src/test/java/school/redrover/LocomotiveGroupTest.java
> +        WebElement inputName = getDriver().findElement(By.xpath("//*[@id=\"name\"]"));
It's not recommended to use unstable locators like li[ ] or div[ ], etc.

2023-10-22 19:58 UTC, EkaterinaSokolova-V approved these changes

2023-11-10 17:53 UTC, closed without merging